
from enum import Enum, auto


class KeywordEnum(Enum):
	FATED = auto()
	KINDRED_MARK = auto()
	TRANSFORM = auto()
	FORMIDABLE = auto()
	ATTACH = auto()
	AURAVISUALFAKEKEYWORD = auto()
	LANDMARKVISUALONLY = auto()
	COUNTDOWN = auto()
	IMPACT = auto()
	FLYING = auto()
	IMBUE = auto()
	LURKER = auto()
	OVERWHELM = auto()
	VULNERABLE = auto()
	ATTUNE = auto()
	BRASH = auto()
	AUGMENT = auto()
	BARRIER = auto()
	CHALLENGER = auto()
	DEEP = auto()
	FURY = auto()
	FEARSOME = auto()
	FLEETING = auto()
	SCOUT = auto()
	STUN = auto()
	ELUSIVE = auto()
	QUICKSTRIKE = auto()
	DOUBLESTRIKE = auto()
	LASTBREATH = auto()
	SPELLSHIELD = auto()
	LIFESTEAL = auto()
	REGENERATION = auto()
	SUPPORT = auto()
	EPHEMERAL = auto()
	TOUGH = auto()
	SLOW = auto()
	FAST = auto()
	BURST = auto()
	FOCUS = auto()
	SPELLOVERWHELM = auto()
	SKILL = auto()
	#---NEGATIVE
	FROSTBITE = auto()
	CANTBLOCK = auto()
	CANT_ATTACK = auto()
	IMMOBILE = auto()
	RANDOM_KEYWORD = auto()